spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/MySiteDB
    username: root
    password: lldj123414
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always #색깔
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        highlight-sql: true
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE